version: '3'
services:
  keystone:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file: .env
    command: 'yarn dev'
    ports:
    - 3000:3000
    volumes:
    - "./lists:/home/node/lists"
    - "./index.js:/home/node/index.js"
    - "./package.json:/home/node/package.json"
    - "./yarn.lock:/home/node/yarn.lock"
